version: "3"
services:
  node-app:
    build: 
      context: .
      args: 
        App_Env: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - App_Env=development
    command : npm run dev
