version: "3"
services:
  node-app:
    build: .
    ports:
      - "8000:4000"
    environment:
      - port=4000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kishan
      - MONGO_INITDB_ROOT_PASSWORD=kishan
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis

volumes:
  mongo-db: